from rest_framework.routers import DefaultRouter
from scheduler.views import ClienteViewSet, HorarioViewSet, VinculoViewSet, BloqueioHorarioViewSet

router = DefaultRouter()  # Cria uma instância do DefaultRouter, que vai ser usado para registrar suas rotas | Creates an instance of DefaultRouter, which will be used to register your routes

router.register(r'clientes', ClienteViewSet)  # Registra a rota 'clientes' associada ao ClienteViewSet | Registers the 'clientes' route associated with the ClienteViewSet
router.register(r'horarios', HorarioViewSet)
router.register(r'vinculos', VinculoViewSet)
router.register(r'bloqueios', BloqueioHorarioViewSet)
# O 'r' antes da string indica que é uma "raw string" (string bruta), que trata caracteres especiais literalmente | The 'r' before the string indicates that it is a "raw string", which treats special characters literally
# Aqui não seria obrigatório usar 'r', porque a string não tem caracteres especiais | Here it is not necessary to use 'r', because the string does not have special characters
# Mas é uma prática comum usar para evitar problemas quando usar regex ou barras invertidas em rotas | but it is common practice to use it to avoid problems when using regex or backslashes in routes

urlpatterns = router.urls
# Atribui as URLs geradas automaticamente pelo router para a variável urlpatterns, que o Django vai usar para definir as rotas do seu app | Assigns the URLs automatically generated by the router to the urlpatterns variable, which Django will use to define the routes of your app