# Generated by Django 5.2.4 on 2025-07-25 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_bloqueiohorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueiohorario',
            name='data',
            field=models.DateField(default=datetime.date(2025, 7, 25)),
            preserve_default=False,
        ),
    ]
